// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateERC20Transfer = `-- name: BatchCreateERC20Transfer :batchexec
INSERT INTO erc20_transfers (tx_hash, log_index, from_address, to_address, value, block_number, token_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tx_hash, log_index) DO UPDATE SET is_canonical = TRUE, reorg_detected_at = NULL
`

type BatchCreateERC20TransferBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateERC20TransferParams struct {
	TxHash       string         `json:"txHash"`
	LogIndex     int32          `json:"logIndex"`
	FromAddress  string         `json:"fromAddress"`
	ToAddress    string         `json:"toAddress"`
	Value        pgtype.Numeric `json:"value"`
	BlockNumber  int64          `json:"blockNumber"`
	TokenAddress string         `json:"tokenAddress"`
}

func (q *Queries) BatchCreateERC20Transfer(ctx context.Context, arg []BatchCreateERC20TransferParams) *BatchCreateERC20TransferBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TxHash,
			a.LogIndex,
			a.FromAddress,
			a.ToAddress,
			a.Value,
			a.BlockNumber,
			a.TokenAddress,
		}
		batch.Queue(batchCreateERC20Transfer, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateERC20TransferBatchResults{br, len(arg), false}
}

func (b *BatchCreateERC20TransferBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateERC20TransferBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
