// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block_operation.sql

package sqlc

import (
	"context"
	"time"
)

const countBlocks = `-- name: CountBlocks :one
SELECT COUNT(*) as count
FROM blocks
`

func (q *Queries) CountBlocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlocks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (hash, number, parent_hash, timestamp)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, hash, number, parent_hash, timestamp
`

type CreateBlockParams struct {
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

type CreateBlockRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.Hash,
		arg.Number,
		arg.ParentHash,
		arg.Timestamp,
	)
	var i CreateBlockRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Number,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE id = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBlock, id)
	return err
}

const deleteBlockByHash = `-- name: DeleteBlockByHash :exec
DELETE FROM blocks
WHERE hash = $1
`

func (q *Queries) DeleteBlockByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteBlockByHash, hash)
	return err
}

const deleteBlocksFromHeight = `-- name: DeleteBlocksFromHeight :exec
DELETE FROM blocks
WHERE number > $1
`

func (q *Queries) DeleteBlocksFromHeight(ctx context.Context, number int64) error {
	_, err := q.db.Exec(ctx, deleteBlocksFromHeight, number)
	return err
}

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT id, hash, number, parent_hash, timestamp
FROM blocks
WHERE hash = $1
`

type GetBlockByHashRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) GetBlockByHash(ctx context.Context, hash string) (GetBlockByHashRow, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, hash)
	var i GetBlockByHashRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Number,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT id, hash, number, parent_hash, timestamp
FROM blocks
WHERE id = $1
`

type GetBlockByIDRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) GetBlockByID(ctx context.Context, id int32) (GetBlockByIDRow, error) {
	row := q.db.QueryRow(ctx, getBlockByID, id)
	var i GetBlockByIDRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Number,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}

const getBlockByNumber = `-- name: GetBlockByNumber :one
SELECT id, hash, number, parent_hash, timestamp
FROM blocks
WHERE number = $1 AND is_canonical = TRUE
`

type GetBlockByNumberRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) GetBlockByNumber(ctx context.Context, number int64) (GetBlockByNumberRow, error) {
	row := q.db.QueryRow(ctx, getBlockByNumber, number)
	var i GetBlockByNumberRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Number,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}

const getLatestBlockNumber = `-- name: GetLatestBlockNumber :one
SELECT MAX(number)::Bigint FROM blocks WHERE is_canonical = TRUE HAVING MAX(number) IS NOT NULL
`

func (q *Queries) GetLatestBlockNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestBlockNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestProcessedBlockNumber = `-- name: GetLatestProcessedBlockNumber :one
SELECT MAX(number)::Bigint FROM blocks WHERE processed_at IS NOT NULL AND is_canonical = TRUE HAVING MAX(number) IS NOT NULL
`

func (q *Queries) GetLatestProcessedBlockNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestProcessedBlockNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, hash, number, parent_hash, timestamp
FROM blocks
WHERE is_canonical = TRUE
ORDER BY number DESC
LIMIT $1 OFFSET $2
`

type ListBlocksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBlocksRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Number,
			&i.ParentHash,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlockFinalized = `-- name: MarkBlockFinalized :exec
UPDATE blocks
SET status = 'FINALIZED'
WHERE number <= $1 AND is_canonical = TRUE AND status != 'FINALIZED'
`

func (q *Queries) MarkBlockFinalized(ctx context.Context, number int64) error {
	_, err := q.db.Exec(ctx, markBlockFinalized, number)
	return err
}

const markBlockProcessed = `-- name: MarkBlockProcessed :exec
UPDATE blocks
SET processed_at = NOW()
WHERE number = $1 AND processed_at IS NULL
`

func (q *Queries) MarkBlockProcessed(ctx context.Context, number int64) error {
	_, err := q.db.Exec(ctx, markBlockProcessed, number)
	return err
}

const markBlockReorgedRange = `-- name: MarkBlockReorgedRange :exec
UPDATE blocks
SET is_canonical = FALSE, reorg_detected_at = NOW()
WHERE number > $1
`

func (q *Queries) MarkBlockReorgedRange(ctx context.Context, number int64) error {
	_, err := q.db.Exec(ctx, markBlockReorgedRange, number)
	return err
}

const updateBlock = `-- name: UpdateBlock :one
UPDATE blocks
SET hash = $2, number = $3, parent_hash = $4, timestamp = $5
WHERE id = $1
RETURNING id, hash, number, parent_hash, timestamp
`

type UpdateBlockParams struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

type UpdateBlockRow struct {
	ID         int32     `json:"id"`
	Hash       string    `json:"hash"`
	Number     int64     `json:"number"`
	ParentHash string    `json:"parentHash"`
	Timestamp  time.Time `json:"timestamp"`
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (UpdateBlockRow, error) {
	row := q.db.QueryRow(ctx, updateBlock,
		arg.ID,
		arg.Hash,
		arg.Number,
		arg.ParentHash,
		arg.Timestamp,
	)
	var i UpdateBlockRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Number,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}
