// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID          int32            `json:"id"`
	Hash        string           `json:"hash"`
	Number      int64            `json:"number"`
	ParentHash  string           `json:"parentHash"`
	Timestamp   time.Time        `json:"timestamp"`
	ProcessedAt pgtype.Timestamp `json:"processedAt"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}
