// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	BatchCreateERC20Transfer(ctx context.Context, arg []BatchCreateERC20TransferParams) *BatchCreateERC20TransferBatchResults
	CountBlocks(ctx context.Context) (int64, error)
	CountERC20Transfers(ctx context.Context) (int64, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error)
	CreateERC20Transfer(ctx context.Context, arg CreateERC20TransferParams) (CreateERC20TransferRow, error)
	DeleteBlock(ctx context.Context, id int32) error
	DeleteBlockByHash(ctx context.Context, hash string) error
	DeleteBlocksFromHeight(ctx context.Context, number int64) error
	DeleteERC20TransfersFromHeight(ctx context.Context, blockNumber int64) error
	GetBlockByHash(ctx context.Context, hash string) (GetBlockByHashRow, error)
	GetBlockByID(ctx context.Context, id int32) (GetBlockByIDRow, error)
	GetBlockByNumber(ctx context.Context, number int64) (GetBlockByNumberRow, error)
	GetERC20Transfer(ctx context.Context, arg GetERC20TransferParams) (GetERC20TransferRow, error)
	GetLatestBlockNumber(ctx context.Context) (int64, error)
	GetLatestProcessedBlockNumber(ctx context.Context) (int64, error)
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error)
	ListERC20TransfersByTxHash(ctx context.Context, arg ListERC20TransfersByTxHashParams) ([]ListERC20TransfersByTxHashRow, error)
	MarkBlockFinalized(ctx context.Context, number int64) error
	MarkBlockProcessed(ctx context.Context, number int64) error
	MarkBlockReorgedRange(ctx context.Context, number int64) error
	MarkERC20TransfersReorgedRange(ctx context.Context, blockNumber int64) error
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) (UpdateBlockRow, error)
}

var _ Querier = (*Queries)(nil)
