// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountBlocks(ctx context.Context) (int64, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error)
	DeleteBlock(ctx context.Context, id int32) error
	DeleteBlockByHash(ctx context.Context, hash string) error
	GetBlockByHash(ctx context.Context, hash string) (GetBlockByHashRow, error)
	GetBlockByID(ctx context.Context, id int32) (GetBlockByIDRow, error)
	GetBlockByNumber(ctx context.Context, number int64) (GetBlockByNumberRow, error)
	GetLatestBlockNumber(ctx context.Context) (int64, error)
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error)
	MarkBlockProcessed(ctx context.Context, number int64) error
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) (UpdateBlockRow, error)
}

var _ Querier = (*Queries)(nil)
